apiVersion: v2
name: covibes
description: Scalable collaborative development platform with AI agents
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql-ha
    version: 11.9.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: redis
    version: 17.11.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: prometheus
    version: 15.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled

  - name: grafana
    version: 6.50.0
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled

keywords:
  - collaboration
  - development
  - ai-agents
  - kubernetes
  - scalable

maintainers:
  - name: Covibes Team
    email: admin@covibes.com

home: https://covibes.com