apiVersion: apps/v1
kind: Deployment
metadata:
  name: covibes-websocket
  labels:
    app: covibes
    component: websocket
spec:
  replicas: 5
  selector:
    matchLabels:
      app: covibes
      component: websocket
  template:
    metadata:
      labels:
        app: covibes
        component: websocket
    spec:
      containers:
      - name: websocket
        image: covibes/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: websocket
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: SERVICE_TYPE
          value: "websocket"
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: covibes-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: covibes-secrets
              key: redis-url
        - name: SOCKET_IO_REDIS_ADAPTER
          value: "true"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: covibes-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: covibes-websocket
  labels:
    app: covibes
    component: websocket
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app: covibes
    component: websocket
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: websocket
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: covibes-websocket-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: covibes-websocket
  minReplicas: 5
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 10
        periodSeconds: 30
      selectPolicy: Max